package model

// Status ...
type Status string

var (
	// StatusDraft ...
	StatusDraft Status = "DRAFT"
	// StatusActive ...
	StatusActive Status = "ACTIVE"
	// StatusArchive ...
	StatusArchive Status = "ARCHIVE"
)
